// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzXRK6vFP4oRdueOe_3QV52ZO68ukDgKQ',
    appId: '1:679380756360:web:da05614e7aef341a83bc3d',
    messagingSenderId: '679380756360',
    projectId: 'student-scratch',
    authDomain: 'student-scratch.firebaseapp.com',
    storageBucket: 'student-scratch.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnHFKhv1eFQ9Br8YZVMY8915O944lPAmQ',
    appId: '1:679380756360:android:1884bdd5c2e99a5b83bc3d',
    messagingSenderId: '679380756360',
    projectId: 'student-scratch',
    storageBucket: 'student-scratch.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUjdcxgR53RKY3jU664xIqYwqiLB8-paM',
    appId: '1:679380756360:ios:a110255a5169df6683bc3d',
    messagingSenderId: '679380756360',
    projectId: 'student-scratch',
    storageBucket: 'student-scratch.appspot.com',
    iosBundleId: 'com.example.studentRegFirbase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUjdcxgR53RKY3jU664xIqYwqiLB8-paM',
    appId: '1:679380756360:ios:a110255a5169df6683bc3d',
    messagingSenderId: '679380756360',
    projectId: 'student-scratch',
    storageBucket: 'student-scratch.appspot.com',
    iosBundleId: 'com.example.studentRegFirbase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzXRK6vFP4oRdueOe_3QV52ZO68ukDgKQ',
    appId: '1:679380756360:web:192b8781d042b2b083bc3d',
    messagingSenderId: '679380756360',
    projectId: 'student-scratch',
    authDomain: 'student-scratch.firebaseapp.com',
    storageBucket: 'student-scratch.appspot.com',
  );

}